const participantsData = [
  { name: "Abdullah Shah", team: "Noorabad Lions", id: 1 },
  { name: "Sabat Ali", team: "Noorabad Lions", id: 1 },
  { name: "Minha Hussain", team: "Noorabad Lions", id: 1 },
  { name: "Aly Soloman", team: "Noorabad Lions", id: 1 },
  { name: "Mishal Hussain", team: "Noorabad Lions", id: 1 },
  { name: "Zoyaan Lakhani", team: "Noorabad Lions", id: 1 },
  { name: "Cainaat Karim", team: "Noorabad Lions", id: 1 },
  { name: "Aahil Akber", team: "Noorabad Lions", id: 1 },
  { name: "Samina Hussain", team: "Noorabad Lions", id: 1 },
  { name: "Saima Baig", team: "Noorabad Lions", id: 1 },
  { name: "Raheel Bhanwadia", team: "Noorabad Lions", id: 1 },
  { name: "Akber Verasia", team: "Noorabad Lions", id: 1 },
  { name: "Dilshad Manek", team: "Noorabad Lions", id: 1 },
  { name: "Salima Saleem", team: "Noorabad Eagel", id: 2 },
  { name: "Faraj Irfan Sheikh", team: "Noorabad Eagel", id: 2 },
  { name: "Imaan Malik", team: "Noorabad Eagel", id: 2 },
  { name: "Marukh", team: "Noorabad Eagel", id: 2 },
  { name: "Arham Khimani", team: "Noorabad Eagel", id: 2 },
  { name: "Alyan Aziz", team: "Noorabad Eagel", id: 2 },
  { name: "Soha Nizar", team: "Noorabad Eagel", id: 2 },
  { name: "Asfi Shadab", team: "Noorabad Eagel", id: 2 },
  { name: "Nayan Navroz", team: "Noorabad Eagel", id: 2 },
  { name: "Hamas", team: "Noorabad Eagel", id: 2 },
  { name: "Sehrin Alwani", team: "Noorabad Eagel", id: 2 },
  { name: "Akber Verasia", team: "Noorabad Eagel", id: 2 },
  { name: "Farzana Sadruddin", team: "Noorabad Eagel", id: 2 },
  { name: "Daniyal Hirani", team: "Noorabad Eagel", id: 2 },
  { name: "Karim Qadir", team: "Noorabad Eagel", id: 2 },
  { name: "Komal Lalani", team: "Noorabad Eagel", id: 2 },
  { name: "Alnoor Ali", team: "Noorabad Eagel", id: 2 },
  { name: "Azeema Zulfiqar", team: "Noorabad Eagel", id: 2 },
  { name: "Aayan Malik", team: "Noorabad Sharks", id: 3 },
  { name: "Eyleen", team: "Noorabad Sharks", id: 3 },
  { name: "Ibrahim Ali", team: "Noorabad Sharks", id: 3 },
  { name: "Izzah Ramzan", team: "Noorabad Sharks", id: 3 },
  { name: "Adyaan Ali", team: "Noorabad Sharks", id: 3 },
  { name: "Mishal Farhan", team: "Noorabad Sharks", id: 3 },
  { name: "Rahim Jindani", team: "Noorabad Sharks", id: 3 },
  { name: "Afsana Bhanwadia", team: "Noorabad Sharks", id: 3 },
  { name: "Danish", team: "Noorabad Sharks", id: 3 },
  { name: "M.Hussnain Sheikh", team: "Noorabad Sharks", id: 3 },
  { name: "Simrah Tejani", team: "Noorabad Sharks", id: 3 },
  { name: "Afsana Bhanwadia", team: "Noorabad Sharks", id: 3 },
  { name: "Mir Fazal", team: "Noorabad Sharks", id: 3 },
  { name: "Zohra Sohail", team: "Noorabad Sharks", id: 3 },
  { name: "Ayman Jiwani", team: "Noorabad Panthers", id: 4 },
  { name: "Asher Malik", team: "Noorabad Panthers", id: 4 },
  { name: "Sheza Pirani", team: "Noorabad Panthers", id: 4 },
  { name: "Sheza Pirani", team: "Noorabad Panthers", id: 4 },
  { name: "Rayan Gillani", team: "Noorabad Panthers", id: 4 },
  { name: "Shawaiz", team: "Noorabad Panthers", id: 4 },
  { name: "Anjiya Karim", team: "Noorabad Panthers", id: 4 },
  { name: "Ayra Rahim", team: "Noorabad Panthers", id: 4 },
  { name: "Sahil Faisal", team: "Noorabad Panthers", id: 4 },
  { name: "Shifa Shadab", team: "Noorabad Panthers", id: 4 },
  { name: "Nuruddin Badrudddin", team: "Noorabad Panthers", id: 4 },
  { name: "Farrida Razzaq", team: "Noorabad Panthers", id: 4 },
  { name: "Ayman Hussain", team: "Noorabad Panthers", id: 4 },
  { name: "Salima Naveed", team: "Noorabad Panthers", id: 4 },
  { name: "Nabeeha", team: "Noorabad Panthers", id: 4 },
  { name: "Akber Vallani", team: "Noorabad Panthers", id: 4 },
  { name: "Navroz Ali", team: "Noorabad Panthers", id: 4 },
  { name: "Laila Ali Ladha", team: "Noorabad Panthers", id: 4 },
  { name: "Laila Alnoor", team: "Noorabad Markhor", id: 5 },
  { name: "Zohan Ali", team: "Noorabad Markhor", id: 5 },
  { name: "Aryaan Nasir", team: "Noorabad Markhor", id: 5 },
  { name: "Shahzay Irfan", team: "Noorabad Markhor", id: 5 },
  { name: "Yabish", team: "Noorabad Markhor", id: 5 },
  { name: "Shanaya Salim", team: "Noorabad Markhor", id: 5 },
  { name: "Abyan Adil", team: "Noorabad Markhor", id: 5 },
  { name: "Izzah Rahim", team: "Noorabad Markhor", id: 5 },
  { name: "Irfan Ramzan", team: "Noorabad Markhor", id: 5 },
  { name: "Saima Malik", team: "Noorabad Markhor", id: 5 },
  { name: "Aymen Merchant", team: "Noorabad Markhor", id: 5 },
  { name: "Najia Amir Ali", team: "Noorabad Markhor", id: 5 },
  { name: "Nabila Padaniya", team: "Noorabad Markhor", id: 5 },
  { name: "Irfan Ramzan", team: "Noorabad Markhor", id: 5 },
  { name: "Saima Malik", team: "Noorabad Markhor", id: 5 },
];

export default participantsData;
